name: Push to Airflow

on:
  workflow_dispatch:

jobs:
  push_to_airflow:
    name: Run push_to_airflow.sh
    runs-on: ubuntu-latest

    permissions:
        contents: 'read' # lets the workflow read our code
        id-token: 'write' # lets the workflow ask GitHub for a temporary token to log in to Google Cloud

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/855475113448/locations/global/workloadIdentityPools/eto-github/providers/eto-github'
          service_account: 'eto-artifact-registry-github@gcp-cset-projects.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Run push_to_airflow.sh
        run: |
          chmod +x ./push_to_airflow.sh
          ./push_to_airflow.sh
